In [1]:
#LEVEL 1
import numpy as np
import os 
import pandas as pd
import matplotlib.pyplot as plt
!pip install scikit-learn

Requirement already satisfied: scikit-learn in C:\Users\user\anaconda3\envs\tshubh\Lib\site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\user\anaconda3\envs\tshubh\Lib\site-packages (from scikit-learn) (2.5.2)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\user\anaconda3\envs\tshubh\Lib\site-packages (from scikit-learn) (1.18.1)
Requirement already satisfied: joblib>=1.4.0 in C:\Users\user\anaconda3\envs\tshubh\Lib\site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in C:\Users\user\anaconda3\envs\tshubh\Lib\site-packages (from scikit-learn) (2.25.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in C:\Users\user\anaconda3\envs\tshubh\Lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: cloudpickle>=3.0 in C:\Users\user\anaconda3\envs\tshubh\Lib\site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)

In [2]:
df = pd.read_excel("Online Retail.xlsx")
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [9]:
df['Country'].nunique()

38

In [119]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[us]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 33.1+ MB

In [120]:
df = df.dropna(subset= ['CustomerID'])
df = df.dropna(subset= ['Description'])
df.info()

<class 'pandas.DataFrame'>
Index: 406829 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    406829 non-null  object
 1   StockCode    406829 non-null  object
 2   Description  406829 non-null  object
 3   Quantity     406829 non-null  int64
 4   InvoiceDate  406829 non-null  datetime64[us]
 5   UnitPrice    406829 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      406829 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 27.9+ MB

In [121]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [122]:
df.tail()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [123]:
df.describe()

            Quantity                 InvoiceDate      UnitPrice     CustomerID
count  406829.000000                      406829  406829.000000  406829.000000
mean       12.061303  2011-07-10 16:30:57.879207       3.460471   15287.690570
min    -80995.000000         2010-12-01 08:26:00       0.000000   12346.000000
25%         2.000000         2011-04-06 15:02:00       1.250000   13953.000000
50%         5.000000         2011-07-31 11:48:00       1.950000   15152.000000
75%        12.000000         2011-10-20 13:06:00       3.750000   16791.000000
max     80995.000000         2011-12-09 12:50:00   38970.000000   18287.000000
std       248.693370                         NaN      69.315162    1713.600303

In [124]:
df.shape

(406829, 8)

In [125]:
df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [126]:
#1. Total Transactions
t_transaction = df['Quantity'] * df['UnitPrice']

In [127]:
#2. Unique Customer
unique_customer = df['CustomerID'].sort_values(ascending = True).unique()

In [128]:
#3. Unique Products
Unique_Products = df['Description'].astype(str).sort_values(ascending = True).unique()

In [129]:
#Unique_Country
Unique_Country = df['Country'].sort_values(ascending=True).unique()

In [130]:
#LEVEL 2

In [131]:
df = df.dropna(subset =['CustomerID'])
df = df.dropna(subset= ['Description'])
df.info()

<class 'pandas.DataFrame'>
Index: 406829 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    406829 non-null  object
 1   StockCode    406829 non-null  object
 2   Description  406829 non-null  object
 3   Quantity     406829 non-null  int64
 4   InvoiceDate  406829 non-null  datetime64[us]
 5   UnitPrice    406829 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      406829 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 27.9+ MB

In [132]:
fit = df['InvoiceNo'].astype(str).str.startswith('C')
df = df[~fit]
df['InvoiceNo'].astype(str).str.startswith('C').sum()

np.int64(0)

In [133]:
filter_by = df['UnitPrice'].astype(int)
filter_b2y = df['Quantity'].astype(int)
compare = (filter_by <= 0) & (filter_b2y <= 0)
df = df[~compare]

In [134]:
compare.sum()

np.int64(0)

In [135]:
#LEVEL 3

In [136]:
df['TotalAmount'] = df['Quantity']* df['UnitPrice']

In [137]:
df.info()

<class 'pandas.DataFrame'>
Index: 397924 entries, 0 to 541908
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    397924 non-null  object
 1   StockCode    397924 non-null  object
 2   Description  397924 non-null  object
 3   Quantity     397924 non-null  int64
 4   InvoiceDate  397924 non-null  datetime64[us]
 5   UnitPrice    397924 non-null  float64
 6   CustomerID   397924 non-null  float64
 7   Country      397924 non-null  str
 8   TotalAmount  397924 non-null  float64
dtypes: datetime64[us](1), float64(3), int64(1), object(3), str(1)
memory usage: 30.4+ MB

In [138]:
#LEVEL 4

In [139]:
No_of_Orders = df.groupby('CustomerID')['InvoiceNo'].count()

In [140]:
Total_Spent = df.groupby('CustomerID')['TotalAmount'].sum()

In [141]:
avg_ord_val = df.groupby('CustomerID')['TotalAmount'].mean()

In [142]:
no_of_product = df.groupby('CustomerID')['Description'].count()

In [143]:
country = df.groupby('CustomerID')['Country'].unique()

In [144]:
#LEVEL 5

In [145]:
df['InvoiceDate'].min()

Timestamp('2010-12-01 08:26:00')

In [146]:
df['InvoiceDate'].max()

Timestamp('2011-12-09 12:50:00')

In [147]:
cut_off_date = pd.Timestamp('2011-12-01 08:26:00')
past = df[df['InvoiceDate'] < cut_off_date]

In [148]:
future = df[df['InvoiceDate'] > cut_off_date]

In [149]:
past.shape

(380620, 9)

In [150]:
future.shape

(17304, 9)

In [151]:
print("Past:", past["InvoiceDate"].min(), "to", past["InvoiceDate"].max())
print("Future:", future["InvoiceDate"].min(), "to", future["InvoiceDate"].max())

Past: 2010-12-01 08:26:00 to 2011-11-30 17:37:00
Future: 2011-12-01 08:33:00 to 2011-12-09 12:50:00

In [152]:
future_customers = future["CustomerID"].unique()

In [153]:
past["WillCustomerPurchaseAgain"] = (past["CustomerID"].isin(future_customers).astype(int))

In [154]:
past[['CustomerID','InvoiceDate','WillCustomerPurchaseAgain']].head(20)

    CustomerID         InvoiceDate  WillCustomerPurchaseAgain
0      17850.0 2010-12-01 08:26:00                          0
1      17850.0 2010-12-01 08:26:00                          0
2      17850.0 2010-12-01 08:26:00                          0
3      17850.0 2010-12-01 08:26:00                          0
4      17850.0 2010-12-01 08:26:00                          0
5      17850.0 2010-12-01 08:26:00                          0
6      17850.0 2010-12-01 08:26:00                          0
7      17850.0 2010-12-01 08:28:00                          0
8      17850.0 2010-12-01 08:28:00                          0
9      13047.0 2010-12-01 08:34:00                          0
10     13047.0 2010-12-01 08:34:00                          0
11     13047.0 2010-12-01 08:34:00                          0
12     13047.0 2010-12-01 08:34:00                          0
13     13047.0 2010-12-01 08:34:00                          0
14     13047.0 2010-12-01 08:34:00                          0
15     13047.0 2010-12-01 08:34:00                          0
16     13047.0 2010-12-01 08:34:00                          0
17     13047.0 2010-12-01 08:34:00                          0
18     13047.0 2010-12-01 08:34:00                          0
19     13047.0 2010-12-01 08:34:00                          0

In [155]:
past['WillCustomerPurchaseAgain'].value_counts(normalize = True)*100

WillCustomerPurchaseAgain
0    66.921339
1    33.078661
Name: proportion, dtype: float64

In [156]:
past['WillCustomerPurchaseAgain'].count()

np.int64(380620)

In [157]:
past['TotalAmount'] = past['Quantity']*past['UnitPrice']

In [158]:
past[['Quantity','UnitPrice','TotalAmount']]

        Quantity  UnitPrice  TotalAmount
0              6       2.55        15.30
1              6       3.39        20.34
2              8       2.75        22.00
3              6       3.39        20.34
4              6       3.39        20.34
...          ...        ...          ...
516364         4       1.25         5.00
516365         2       5.95        11.90
516366         6       2.08        12.48
516367         1       7.95         7.95
516368         1       5.95         5.95

[380620 rows x 3 columns]

In [159]:
customer_features = past.groupby('CustomerID').agg(No_of_order = ('InvoiceNo', 'nunique'), Total_spent = ('TotalAmount','sum'))
customer_features.head()

            No_of_order  Total_spent
CustomerID
12346.0               1     77183.60
12347.0               6      4085.18
12348.0               4      1797.24
12349.0               1      1757.55
12350.0               1       334.40

In [160]:
customer_features['AvgOrdVal'] = customer_features['Total_spent'] / customer_features['No_of_order']

In [161]:
uni_product = past.groupby('CustomerID')['StockCode'].nunique()

In [162]:
uni_product = past.groupby('CustomerID')['Description'].nunique()
customer_features['UniqueProducts'] = uni_product

In [163]:
TargetCustomer = past.groupby('CustomerID')['WillCustomerPurchaseAgain'].count()

In [164]:
TargetCustomer = past.groupby('CustomerID')['WillCustomerPurchaseAgain'].sum()

In [165]:
TargetCustomer = past.groupby('CustomerID')['WillCustomerPurchaseAgain'].max()

In [166]:
customer_features['WillCustomerPurchaseAgain'] = TargetCustomer
customer_features.head()

,No_of_order,Total_spent,AvgOrdVal,UniqueProducts,WillCustomerPurchaseAgain
CustomerID,,,,,
12346.0,1,77183.60,77183.600000,1,0
12347.0,6,4085.18,680.863333,100,1
12348.0,4,1797.24,449.310000,22,0
12349.0,1,1757.55,1757.550000,73,0
12350.0,1,334.40,334.400000,17,0

In [167]:
customer_features.describe()

,No_of_order,Total_spent,AvgOrdVal,UniqueProducts,WillCustomerPurchaseAgain
count,4298.000000,4298.000000,4298.000000,4298.000000,4298.000000
mean,4.131689,1952.818779,400.255621,60.426245,0.133550
std,7.420253,8354.913254,1271.187289,84.050035,0.340208
min,1.000000,0.000000,0.000000,1.000000,0.000000
25%,1.000000,304.305000,178.602500,16.000000,0.000000
50%,2.000000,657.265000,295.033958,35.000000,0.000000
75%,4.000000,1599.515000,431.594250,76.000000,0.000000
max,201.000000,268478.000000,77183.600000,1762.000000,1.000000

In [168]:
customer_features.isnull().count()

No_of_order                  4298
Total_spent                  4298
AvgOrdVal                    4298
UniqueProducts               4298
WillCustomerPurchaseAgain    4298
dtype: int64

In [169]:
customer_features.info()

<class 'pandas.DataFrame'>
Index: 4298 entries, 12346.0 to 18287.0
Data columns (total 5 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   No_of_order                4298 non-null   int64
 1   Total_spent                4298 non-null   float64
 2   AvgOrdVal                  4298 non-null   float64
 3   UniqueProducts             4298 non-null   int64
 4   WillCustomerPurchaseAgain  4298 non-null   int64
dtypes: float64(2), int64(3)
memory usage: 201.5 KB

In [170]:
X = customer_features[['No_of_order','Total_spent','AvgOrdVal','UniqueProducts']]
y = customer_features[['WillCustomerPurchaseAgain']]

In [171]:
X.head()

            No_of_order  Total_spent     AvgOrdVal  UniqueProducts
CustomerID
12346.0               1     77183.60  77183.600000               1
12347.0               6      4085.18    680.863333             100
12348.0               4      1797.24    449.310000              22
12349.0               1      1757.55   1757.550000              73
12350.0               1       334.40    334.400000              17

In [172]:
y.head()

            WillCustomerPurchaseAgain
CustomerID
12346.0                             0
12347.0                             1
12348.0                             0
12349.0                             0
12350.0                             0

In [173]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(
    X,
    y,
    test_size = 0.2,
    random_state = 42,
    stratify = y
    
)

In [174]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=1000)
model.fit(X_train,y_train.values.ravel())

LogisticRegression(max_iter=1000)

In [175]:
y_pred = model.predict(X_test)

In [176]:
print(y_pred[:20])

[0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0]

In [177]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test,y_pred)
print(f"Accuracy : {accuracy}")

Accuracy : 0.877906976744186

In [178]:
from sklearn.metrics import(precision_score,recall_score,f1_score)
print(f"Precision : {precision_score(y_test,y_pred)}")
print(f"Recall : {recall_score(y_test,y_pred)}")
print(f"F1 : {f1_score(y_test,y_pred)}")

Precision : 0.6470588235294118
Recall : 0.19130434782608696
F1 : 0.2953020134228188

In [179]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
cm

array([[733,  12],
       [ 93,  22]])

In [180]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.89      0.98      0.93       745
           1       0.65      0.19      0.30       115

    accuracy                           0.88       860
   macro avg       0.77      0.59      0.61       860
weighted avg       0.86      0.88      0.85       860

In [181]:
from sklearn.tree import DecisionTreeClassifier
tree_model = DecisionTreeClassifier(
    max_depth = 5,
    random_state = 42
)

tree_model.fit(X_train,y_train)
tree_pred = tree_model.predict(X_test)

In [182]:
tree_pred[:20]

array([0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [183]:
print('accuracy_score',accuracy_score(y_test,tree_pred))
print('precision_score',precision_score(y_test,tree_pred))
print('recall_score',recall_score(y_test,tree_pred))
print('f1_score',f1_score(y_test,tree_pred))
print(classification_report(y_test,tree_pred))

accuracy_score 0.8732558139534884
precision_score 0.5652173913043478
recall_score 0.22608695652173913
f1_score 0.32298136645962733
              precision    recall  f1-score   support

           0       0.89      0.97      0.93       745
           1       0.57      0.23      0.32       115

    accuracy                           0.87       860
   macro avg       0.73      0.60      0.63       860
weighted avg       0.85      0.87      0.85       860

In [184]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(
    n_estimators = 100,
    max_depth = 5,
    random_state = 42
)
rfc.fit(X_train,y_train.values.ravel())
rfc_pred = rfc.predict(X_test)

In [185]:
 rfc_pred[:20]

array([0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

            WillCustomerPurchaseAgain
CustomerID
16392.0                             0
17739.0                             0
13521.0                             1
13319.0                             1
15052.0                             0
15689.0                             0
16161.0                             1
17859.0                             0
14965.0                             0
12722.0                             0
16611.0                             0
14593.0                             0
12377.0                             0
17317.0                             0
13078.0                             1
12756.0                             0
13070.0                             0
12352.0                             0
17392.0                             0
16951.0                             0

In [187]:
print('accuracy_score',accuracy_score(y_test,rfc_pred))
print('precision_score',precision_score(y_test,rfc_pred))
print('recall_score',recall_score(y_test,rfc_pred))
print('f1_score',f1_score(y_test,rfc_pred))
print(classification_report(y_test,rfc_pred))

accuracy_score 0.8848837209302326
precision_score 0.7222222222222222
recall_score 0.22608695652173913
f1_score 0.3443708609271523
              precision    recall  f1-score   support

           0       0.89      0.99      0.94       745
           1       0.72      0.23      0.34       115

    accuracy                           0.88       860
   macro avg       0.81      0.61      0.64       860
weighted avg       0.87      0.88      0.86       860

In [188]:
results = pd.DataFrame({'Models':['Logistic Regression', 'Decision Tree', 'Random Forest'],
                       'Accuracy':[accuracy_score(y_test,y_pred),
                                  accuracy_score(y_test,tree_pred),
                                  accuracy_score(y_test,rfc_pred)],
                       'Precision':[precision_score(y_test,y_pred),
                                   precision_score(y_test,tree_pred),
                                   precision_score(y_test,rfc_pred)],
                       'Recall':[recall_score(y_test,y_pred),
                                recall_score(y_test,tree_pred),
                                recall_score(y_test,rfc_pred)],
                       'F1':[f1_score(y_test,y_pred),
                            f1_score(y_test,tree_pred),
                            f1_score(y_test,rfc_pred)]
                       })
print(results)

                Models  Accuracy  Precision    Recall        F1
0  Logistic Regression  0.877907   0.647059  0.191304  0.295302
1        Decision Tree  0.873256   0.565217  0.226087  0.322981
2        Random Forest  0.884884   0.722222  0.226087  0.344371

In [189]:
customer_features.info()

<class 'pandas.DataFrame'>
Index: 4298 entries, 12346.0 to 18287.0
Data columns (total 5 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   No_of_order                4298 non-null   int64
 1   Total_spent                4298 non-null   float64
 2   AvgOrdVal                  4298 non-null   float64
 3   UniqueProducts             4298 non-null   int64
 4   WillCustomerPurchaseAgain  4298 non-null   int64
dtypes: float64(2), int64(3)
memory usage: 201.5 KB

In [190]:
new_customer = pd.DataFrame({
    "No_of_order": [7, 1, 12, 2, 9, 1, 5, 2, 15, 3],
    "Total_spent": [2500, 120, 5200, 350, 3100, 75, 1800, 220, 7500, 600],
    "AvgOrdVal": [357.14, 120, 433.33, 175, 344.44,
                          75, 360, 110, 500, 200],
    "UniqueProducts": [42, 5, 85, 12, 60, 3, 35, 8, 120, 18]
})

In [191]:
Prediction = rfc.predict(new_customer)
Prediction

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0])

In [192]:
Probabilty = rfc.predict_proba(new_customer)
Probabilty

array([[0.78747314, 0.21252686],
       [0.95664843, 0.04335157],
       [0.68164174, 0.31835826],
       [0.94929622, 0.05070378],
       [0.72917258, 0.27082742],
       [0.96131543, 0.03868457],
       [0.82778495, 0.17221505],
       [0.95696397, 0.04303603],
       [0.43159077, 0.56840923],
       [0.91749253, 0.08250747]])